### ISSUE TITLE
ACE fails on "nested" mode

### ISSUE THREAD

**Issue by squizz617** [utsaslab/crashmonkey#125]
Hi, here to report another bug.

Command `python ace.py -l 1 -n True -d False` fails with the following message:
```
Traceback (most recent call last):
  File "ace.py", line 1463, in <module>
    main()
  File "ace.py", line 1422, in main
    doPermutation(i)
  File "ace.py", line 1216, in doPermutation
    modified_pos = satisfyDep(seq, i, modified_sequence, modified_pos, open_dir_map, open_file_map, file_length_map)
  File "ace.py", line 827, in satisfyDep
    modified_pos = checkParentExistsDep(current_sequence, pos, modified_sequence, modified_pos, open_dir_map, open_file_map, file_length_map)
  File "ace.py", line 589, in checkParentExistsDep
    file_name = file_names[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by jayashreemohan29** [comment]
Thanks for notifying. It has been fixed now - #127
